export default {
  login: "TimothySiskin",
  id: 70346998,
  node_id: "MDQ6VXNlcjcwMzQ2OTk4",
  avatar_url: "https://avatars.githubusercontent.com/u/70346998?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/TimothySiskin",
  html_url: "https://github.com/TimothySiskin",
  followers_url: "https://api.github.com/users/TimothySiskin/followers",
  following_url:
    "https://api.github.com/users/TimothySiskin/following{/other_user}",
  gists_url: "https://api.github.com/users/TimothySiskin/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/TimothySiskin/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/TimothySiskin/subscriptions",
  organizations_url: "https://api.github.com/users/TimothySiskin/orgs",
  repos_url: "https://api.github.com/users/TimothySiskin/repos",
  events_url: "https://api.github.com/users/TimothySiskin/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/TimothySiskin/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 3,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2020-08-27T20:17:05Z",
  updated_at: "2021-03-09T19:09:42Z",
};
